apiVersion: v1
kind: Service
metadata:
  name: banking-app-service
spec:
  type: NodePort
  selector:
    app: banking-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008
